name: setup python
description: setup python with uv

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install package and dependencies
      shell: bash
      run: |
        uv pip install --upgrade pip
        uv pip install -r requirements.txt
