name: On PR

# TODO: consider about main branch
on: pull_request

permissions:
  contents: write

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  create-bench:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: ./.github/actions/setup-python

      - name: Create benchmark
        uses: ./.github/actions/create-bench
        with:
          benchmark-filename: ${{ matrix.runner }}.json

  gather-bench:
    needs: create-bench
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Gather benchmark
        uses: ./.github/actions/gather-bench
        with:
          gathered-filename: result.json
